- name: Install aziot-edged 
  apt:
    name:
      - "{{ iotedge_version }}"
      - "{{ identity_service_version }}"
    update_cache: yes
  async: 180
  become: yes
  notify: activate aziot-edged service
- name: Create storage directory for iotedge modules
  file:
    path: /etc/iotedge/storage
    state: directory
    owner: '1000'
    group: iotedge
    mode: "700"