- name: Create fuse tmp directory if it does not exist
  file:
    path: /mnt/azure/fusetmp/calibration
    state: directory
    mode: '0600'

- name: Create fuse_connections directory if it does not exist
  file:
    path: /etc/fuse_connections
    state: directory
    mode: '0755'

- name: Copy config
  copy:
    src: includes/fuse_connections/calibration.cfg
    dest: /etc/fuse_connections/calibration_fuse.cfg
    group: root
    mode: '0600'

- name: Create mount directory if it does not exist
  file:
    path: /mnt/azure/calibration
    state: directory
    mode: '0755'

- name: Copy script
  copy:
    src: includes/blobfuse_scripts/mount_calibration.sh
    dest: /opt/ibm/mount_calibration.sh
    group: root
    mode: '0755'

- name: Mount calibration storage from the cloud
  shell: /opt/ibm/mount_calibration.sh
  become: true

- name: Add to fstab and mount
  mount:
    src: /opt/ibm/mount_calibration.sh
    path: /mnt/azure/calibration
    opts: _netdev
    state: mounted
    fstype: fuse