- name: Install nvme-cli, smartmontools and lm-sensors for telegraf smart plugin
  apt:
    name: ["nvme-cli", "smartmontools", "lm-sensors"]
    update_cache: yes
  async: 180
  become: yes

- name: Prevent telegraf from being upgraded
  dpkg_selections:
    name: telegraf
    selection: install