- name: Install nfs dependency
  apt:
    name: ["nfs-common"]
    update_cache: yes
  async: 180
  become: yes

- name: Mount an NFS volume
  mount:
    fstype: nfs4
    opts: defaults
    state: mounted
    src: 192.168.8.251:/mnt/data/sgre
    path: /mnt/nfs_share
