# Install azure-fuse
- hosts: "{{ variable_hosts | default('all') }}"
  become: true
  roles:
    - ms-repo
    - azure-fuse
    - mount-devstorageoptical
    - role: mount-storage
      mount_name: models
      fuse_cfg_name: mlmodels_fuse.cfg
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: cad
      fuse_cfg_name: cad_data_fuse.cfg
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: retrain
      fuse_cfg_name: retrain_fuse.cfg    
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: work-instructions
      fuse_cfg_name: workinstructions_fuse.cfg
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: calibration
      fuse_cfg_name: calibration_fuse.cfg
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: camera-params
      fuse_cfg_name: camera_params_fuse.cfg
      mount_folder: /mnt/azure