trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
 # FABRIC_CFG_PATH: /usr/local/config

steps:
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'ANSIBLEVMSSH'
      contents: '**'
      readyTimeout: '20000'