trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  FABRIC_CFG_PATH: /usr/local/config

steps:

  - script: |
- task: SSH@0
  inputs:
    runOptions: 'inline'
    inline: 'ansible-playbook -i env/prod/leh/hosts playbooks/shared/01_users.yml --extra-vars "@includes/default-user.json" -Kk --extra-vars "variable_hosts=PRODOB001XFRL4"'
    readyTimeout: '20000'


