
# A pipeline with no CI trigger
trigger:
- none
pool:
  name: 'linux_ob'
steps:
  - script: sudo apt-get update && sudo apt-get install -y moreutils
    displayName: Install Ubuntu dependencies
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
    displayName: Use Python 3.x
  - script: pip install ansible docker
    displayName: Install Python dependencies

 

 



