- name: az login
  shell: az login --service-principal --username {{ client_id }} --password {{ client_password }} --tenant {{ tenant_id }}

- name: az subscription
  shell: az account set --subscription {{ subscription_id }}
  
- name: Retrieve connection string
  shell: az config set extension.use_dynamic_install=yes_without_prompt && az iot hub device-identity connection-string show --device-id {{ deviceid }} --hub-name {{ iothub_name }} --key-type primary --resource-group {{ resource_group }} --query [connectionString] -o tsv
  register: connection_string

- name: Reconfigure IoT Edge
  shell: |
      iotedge config mp --connection-string "{{ connection_string.stdout }}" --force
      iotedge config apply -c '/etc/aziot/config.toml'
  become: yes

- name: Searching for a String
  lineinfile:
    path: /etc/aziot/config.toml
    regexp: '^upstreamProtocol*whatever'
    state: absent
  check_mode: yes
  changed_when: false
  register: upstreamProtocol

- name: Write upstreamProtocol in file
  become: yes
  lineinfile:
    path: /etc/aziot/config.toml
    insertafter: imagePullPolicy = "on-create"
    line: upstreamProtocol = "AmqpWs"
    state: present
  when: not upstreamProtocol.found

- name: restart aziot-edge service
  become: yes
  service:
    name: aziot-edged
    state: restarted