- hosts: "{{ variable_hosts | default('all') }}"
  become: true
  tasks:
    - name: Unhold packages #When ansible 2.13 will be available, this part will be deleted
      dpkg_selections:
        name: "{{ item }}"
        selection: install
      loop:
          - moby-cli
          - moby-containerd
          - moby-engine
          - moby-runc
          - iotedge
          - linux-headers-generic
          - linux-image-generic
          - nvidia-driver-515
          - nvidia-container-runtime
          - nvidia-container-toolkit
          - cuda
    - name: Install specific versions of packages
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day
        #allow_change_held_packages: true #can be enabled in ansible 2.13
        allow_downgrades: true
        name:
          - moby-cli=20.10.16+azure-3
          - moby-containerd=1.5.11+azure-1
          - moby-engine=20.10.16+azure-2
          - moby-runc=1.0.3+azure-1 
          - iotedge=1.1.13-1
          - linux-headers-generic=5.4.0.113.117
          - linux-image-generic=5.4.0.113.117
          - nvidia-driver-515=515.43.04-0ubuntu1
          - nvidia-container-runtime=3.9.0-1
          - nvidia-container-toolkit=1.9.0-1 
          - cuda=11.7.0-1
        state: present
    - name: Prevent packages from being upgraded
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
          - moby-cli
          - moby-containerd
          - moby-engine
          - moby-runc
          - iotedge
          - linux-headers-generic
          - linux-image-generic
          - nvidia-driver-515
          - nvidia-container-runtime
          - nvidia-container-toolkit
          - cuda