- hosts: "{{ variable_hosts | default('all') }}"
  become: yes

  roles:
    - groups
  
  tasks:
  - include_vars: ../../includes/users.yml
  - name: Creating users on target edge machine
    user: 
      name: "{{ item.username}}"
      groups: "{{ item.groups }}"
      shell: /bin/bash
      expires: -1
    with_items: "{{ users }}"

  - name: Placing SSH Key to Authorized Key
    authorized_key: user="{{item.username}}" key="{{ lookup('file', '../../includes/keyfiles/{{ item.username}}.pub')}}"
    with_items: "{{ users }}"

  - name: Add users to docker group
    shell: usermod -aG docker {{item.username}}
    with_items: "{{ users }}"

  - name: Add users to iotedge group
    shell: usermod -aG iotedge {{item.username}}
    with_items: "{{ users }}"

  - name: Disable password expiration
    shell: chage -E -1 -M -1 {{item.username}}
    with_items: "{{ users }}"    