# ansible-os-hardening.yaml
- hosts: "{{ variable_hosts | default('all') }}"
  become: true
  roles:
    - dev-sec.os-hardening

# ansible-ssh-hardening.yaml 
- hosts: "{{ variable_hosts | default('all') }}"
  become: true
  roles:
    - dev-sec.ssh-hardening
  vars:
    ssh_server_password_login: true
    sshd_authenticationmethods: 'publickey password'
    sftp_enabled: true
    ssh_allow_tcp_forwarding: 'yes'
    ssh_x11_forwarding: true
