- hosts: "{{ variable_hosts | default('all') }}"
  become: true
  roles:
    - oefenweb.fail2ban
  vars:
    fail2ban_services:
      - name: sshd
        port: 22
        maxretry: 5
        bantime: 300
