- hosts: "{{ variable_hosts | default('all') }}"
  become: true
  vars_prompt:
  - name: prosoft_mount_username
    prompt: Prosoft mount username
    private: no
  - name: prosoft_mount_password
    prompt: Prosoft mount password
  tasks:
    - name: Create mounts
      include_role:
        name: mount-laser-share
      vars:
        mount_info: "{{ item }}"
      with_items:
        - name: hall10-b9701u2
          mount_dir: /mnt/prosoft
          ip: 192.168.8.5
          username: "{{ prosoft_mount_username }}"
          password: "{{ prosoft_mount_password }}"
          target_dir: B97-01_OpticalBlade
        - name: hall10-b9702u2
          mount_dir: /mnt/prosoft
          ip: 192.168.8.7
          username: "{{ prosoft_mount_username }}"
          password: "{{ prosoft_mount_password }}"
          target_dir: B97-01_OpticalBlade
        - name: hall10-b9702u1
          mount_dir: /mnt/prosoft
          ip: 192.168.8.4
          username: "{{ prosoft_mount_username }}"
          password: "{{ prosoft_mount_password }}"
          target_dir: B97-01_OpticalBlade