- hosts: "{{ variable_hosts | default('all') }}"
  become: true
  roles:
    - ms-repo
    - azure-fuse
    - azure-cli
    - role: mount-storage
      mount_name: models
      container_name: mlmodels
      fuse_cfg_name: mlmodels_fuse.cfg
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: retrain
      container_name: retrain
      fuse_cfg_name: retrain_fuse.cfg
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: calibration
      container_name: calibration-data
      fuse_cfg_name: calibration_fuse.cfg
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: camera-params
      container_name: camera-params
      fuse_cfg_name: camera_params_fuse.cfg
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: data-provisioning
      container_name: data-provisioning-data
      fuse_cfg_name: data_provisioning_fuse.cfg
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: blade-design
      container_name: blade-design-data
      fuse_cfg_name: blade_design_fuse.cfg
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: system-config
      container_name: system-config
      fuse_cfg_name: system_config_fuse.cfg
      mount_folder: /mnt/azure
    - role: mount-storage
      mount_name: message-output
      container_name: message-output-{{  deviceid.split("-")[-1] | lower }}
      fuse_cfg_name: message_output_fuse.cfg
      mount_folder: /mnt/azure