- hosts: dkaaldev2
  become: yes
  tasks:
  - name: az login
    shell: az login --service-principal --username "" --password "" --tenant "12f921d8-f30d-4596-a652-7045b338485a"
  - name: az subscription
    shell: az account set --subscription "cbe9d379-0f71-4dbc-994b-804713d41dec"
    register: sas_token    
  - name: retrieve date
    command: date +'%Y-%m-%d' -d '+7 days'
    register: end_date
  - name: retrieve secret
    shell: az storage container generate-sas --account-name stdevdvlgenobawe01trrfrm --name armtemplate --permissions acdlrw --expiry {{ end_date.stdout }} --auth-mode login --as-user
    register: sas_token