- hosts: "{{ variable_hosts | default('all') }}"
  become: true
  roles:
    - install-jq
    - install-nload
    - install-log-formatter
    - install-iotedge-reset
    - install-iotedge-reset-1.2
    - install-nvtop
