- name: Install iotedge
  apt:
    name:
      - aziot-edge=1.2.10-1
      - aziot-identity-service=1.2.6-1
    update_cache: yes
  async: 180
  become: yes
  notify: activate iotedge service
- name: Create storage directory for iotedge modules
  file:
    path: /etc/iotedge/storage
    state: directory
    owner: '1000'
    group: iotedge
    mode: "700"