- name: Download MS product repository
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/18.04/multiarch/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb
- name: Install MS product repository
  apt: deb=/tmp/packages-microsoft-prod.deb
  become: true
- name: Make sure HTTPS is supported by apt
  apt:
    name: apt-transport-https
    state: present
    update_cache: no
  become: true