- name: Download MS product repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main
    state: present
- name: Make sure HTTPS is supported by apt
  apt:
    name: apt-transport-https
    state: present
    update_cache: no
  become: true