- name: Add telegraf to docker group
  shell: usermod -aG docker telegraf

- name: Create telegraf.d directory if it does not exist
  file:
    path: /etc/telegraf/telegraf.d/
    state: directory
    mode: '0755'

- name: Copy {{ stage }} {{ location }} specific config
  copy:
    src: "../../env/{{ stage }}/{{ location }}/telegraf.conf"
    dest: "/etc/telegraf/telegraf.d/{{ stage }}-{{ location }}.conf"
    group: telegraf
    owner: telegraf
    mode: '0640'

- name: Create /opt/sgre/telegraf/ directory if it does not exist
  file:
    path: /opt/sgre/telegraf/
    state: directory
    mode: '0755'

- name: Copy telegraf script check-mount.sh
  copy:
    src: ../../includes/check-mount.sh
    dest: /opt/sgre/telegraf/check-mount.sh
    group: root
    mode: '0755'

- name: Copy telegraf script check-container.sh
  copy:
    src: ../../includes/check-container.sh
    dest: /opt/sgre/telegraf/check-container.sh
    group: root
    mode: '0755'    

- name: Copy telegraf script check-nvidia.sh
  copy:
    src: ../../includes/check-nvidia.sh
    dest: /opt/sgre/telegraf/check-nvidia.sh
    group: root
    mode: '0755'    

- name: Copy telegraf script check-space.sh
  copy:
    src: ../../includes/check-space.sh
    dest: /opt/sgre/telegraf/check-space.sh
    group: root
    mode: '0755'    

- name: Copy telegraf sudoers
  copy:
    src: ../../includes/telegraf-sudoers
    dest: /etc/sudoers.d/telegraf
    owner: root
    group: root
    mode: ug+rwX,o=
    force: yes

- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: Prevent telegraf from being upgraded
  dpkg_selections:
    name: telegraf
    selection: hold