- name: Create fuse tmp directory if it does not exist
  file:
    path: /mnt/azure/devstorageoptical-fusetmp
    state: directory
    mode: '0600'

- name: Create fuse_connections directory if it does not exist
  file:
    path: /etc/fuse_connections
    state: directory
    mode: '0755'

- name: Copy config
  copy:
    src: includes/fuse_connections/devstorageoptical.cfg
    dest: /etc/fuse_connections/devstorageoptical_fuse.cfg
    group: root
    mode: '0600'

- name: Create mount directory if it does not exist
  file:
    path: /mnt/azure/devstorageoptical
    state: directory
    mode: '0755'

- name: Create mount directory if it does not exist
  file:
    path: /mnt/azure/devstorageoptical
    state: directory
    mode: '0755'

- name: Copy script
  copy:
    src: includes/blobfuse_scripts/mount_devstorageoptical.sh
    dest: /opt/ibm/mount_devstorageoptical.sh
    group: root
    mode: '0755'

- name: Mount devstorageopticaldata storage from the cloud
  shell: /opt/ibm/mount_devstorageoptical.sh
  become: true

- name: Add to fstab and mount
  mount:
    src: /opt/ibm/mount_devstorageoptical.sh
    path: /mnt/azure/devstorageoptical
    opts: _netdev
    state: mounted
    fstype: fuse